
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace MatchiDataProvider
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public  class post_thread
    {
        [Key]
        public int  user_id { get; set; }
        public string user_avatar_url { get; set; }
        public string message { get; set; }
        public   DateTime  sent_date { get; set; }
        public long thread_id { get; set; }
    }
}
