
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace MatchiDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_follower
    {
        public Nullable<int> user_id { get; set; }
        public Nullable<int> follower_user_id { get; set; }
        public string follower_user_handle { get; set; }
        public string follower_user_avatar { get; set; }
        public string follower_full_name { get; set; }

        [System.ComponentModel.DataAnnotations.Key]
        public long user_followers_id { get; set; }
        public Nullable<bool> flag { get; set; }
        public string user_handle { get; set; }
        public string user_full_name { get; set; }
        public string user_avatar { get; set; }
    }
}
