//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class matchiEntities : DbContext
    {
        public matchiEntities()
            : base("name=matchiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lookup_table_keys> lookup_table_keys { get; set; }
        public virtual DbSet<post_categories> post_categories { get; set; }
        public virtual DbSet<post_thread> post_thread { get; set; }
        public virtual DbSet<post_types> post_types { get; set; }
        public virtual DbSet<topic> topics { get; set; }
        public virtual DbSet<user_bookmarks> user_bookmarks { get; set; }
        public virtual DbSet<user_followers> user_followers { get; set; }
        public virtual DbSet<user_following> user_following { get; set; }
        public virtual DbSet<user_interests> user_interests { get; set; }
        public virtual DbSet<user_locations> user_locations { get; set; }
        public virtual DbSet<user_post_likes> user_post_likes { get; set; }
        public virtual DbSet<user_posts> user_posts { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual ObjectResult<getNearbyPosts_Result> getNearbyPosts(Nullable<decimal> longitude, Nullable<decimal> latitude, Nullable<int> distance_in_km)
        {
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(decimal));
    
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(decimal));
    
            var distance_in_kmParameter = distance_in_km.HasValue ?
                new ObjectParameter("distance_in_km", distance_in_km) :
                new ObjectParameter("distance_in_km", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getNearbyPosts_Result>("getNearbyPosts", longitudeParameter, latitudeParameter, distance_in_kmParameter);
        }
    }
}
