//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [Key]
        public long user_id { get; set; }
        public string user_handle { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string date_joined { get; set; }
        public Nullable<int> follower_count { get; set; }
        public string hearts_count { get; set; }
        public string post_count { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string user_avatar_url { get; set; }
        public Nullable<int> user_type_id { get; set; }
        public string about { get; set; }
    }
}
