//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_following
    {
        public Nullable<int> user_id { get; set; }
        public Nullable<int> following_user_id { get; set; }
        public string following_user_handle { get; set; }
        public string following_user_avatar { get; set; }
        public string following_full_name { get; set; }
        public long user_following_id { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
